### ISSUE TITLE
Problen when I compile Template

### ISSUE THREAD

**Issue by vallamete** [VCVRack/Template#13]
When I compile Template I get error:

The syntax of the command is not correct.
../../compile.mk:56: recipe for target 'build/src/Template.cpp.o' failed
mingw32-make.exe: *** [build/src/Template.cpp.o] Error 1

compile.mk:

55 build/%.cpp.o: %.cpp
56	@mkdir -p $(@D)
57	$(CXX) $(CXXFLAGS) -c -o $@ $<

I don`t know that is this.

**Comment by AndrewBelt** [comment]
Post the result of `make --version`. Also, see https://github.com/VCVRack/Rack/issues/730

**Comment by vallamete** [comment]
I am use Dev-Cpp 5.11 TDM-GCC 4.9.2:
Makefile Processor: C:\Program Files (x86)\Dev-Cpp\MinGW64\bin\mingw32-make.exe


How does Template.cpp connect with that main?

**Comment by AndrewBelt** [comment]
>Dev-Cpp

Well, there's your problem.

**Comment by vallamete** [comment]
I had not read this: https://github.com/VCVRack/Rack/blob/master/README.md

Now I get the following error with MSYS2-mingw64:

$ make -f C:/Users/Usuario/Template/Makefile
g++ -o plugin.dll   -shared -LC:/Users/Usuario/Rack -lRack
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lRack
collect2.exe: error: ld returned 1 exit status
make: *** [C:/Users/Usuario/Rack/compile.mk:47: plugin.dll] Error 1

Ideas?

**Comment by AndrewBelt** [comment]
You need to build Rack before building plugins. If you follow the README carefully, everything will work.

**Comment by vallamete** [comment]
After installing MSYS2, I install Git. Git also installs mingw64 and seems to be making interference. Then I have uninstalled MSYS2 and I have reinstalled MSYS2. Now I compile successful.

I put plugin.dll and res/MyModule.svg in the plugin folder of Rack 0.5.1 and I can not see the plugin in the Rack window.

**Comment by djpeterso23662** [comment]
Hi @vallamete! This is by design. Due to API changes, you must build separately for 0.5.1 and 0.6.0, including building Rack fully.
