### ISSUE TITLE
Getting started questions, dist command not found

### ISSUE THREAD

**Issue by anagrammodular** [VCVRack/Template#18]
Hey guys, I am sorry for the noobish question here - I am new to tools like MSYS2 and having to muck about in makefiles and the like. But I have experience coding and with DSP as well. 

Here's my problem - I went through the steps in the Setting up Your Development Environment section (Windows 10) with success. MSYS2 is up and running. I downloaded the SDK, unzipped it and placed it in my Documents/Rack folder (which also contains the plugins folder, not sure if this is the right place for the SDK or not). I also downloaded the Template-0.6 folder and placed that in the plugins folder. 

At this point in time, I'm not sure how I'm supposed to proceed - the Plugin Development Tutorial seems to imply that I should now continue on to the Building Plugins section, but that section seems to be only for when you build Rack from source? In the forum it seems to suggest that you can use MSYS2 to navigate to your plugin folder and run the command 

RACK_DIR=<Rack SDK path> make dist

I have done this and I get the response 

> bash: dist: command not found

A file named "make" appears in the Template-0.6 folder, but it has 0KB and appears to be completely empty. If I run the command without the 'dist' at the end, there is no error message, but nothing really seems to happen, either. 

Thanks for your time, and again, I apologize for asking such a simple question.

**Comment by AndrewBelt** [comment]
The [Rack SDK instructions](https://github.com/VCVRack/Rack/issues/258#issuecomment-376293898) say

>`RACK_DIR=<Rack SDK path> make dist`

You've completely omitted the Rack SDK path. How is the build system supposed to know where the SDK is on your hard drive?

**Comment by AndrewBelt** [comment]
In command-line syntax, when something is surrounded by <>, remove the brackets.

Secondly, Make doesn't like spaces. Move your workspace to a directory not containing spaces.

**Comment by anagrammodular** [comment]
I got it working, thank you for the fast and helpful support. I knew it would be something embarrassing like that...
