### ISSUE TITLE
Custom Widget : Inherit from where?

### ISSUE THREAD

**Issue by interstar** [VCVRack/Template#19]
I'm coming back to and trying to work on a new module, which needs a custom widget, which I'm trying to figure out from looking at the source code. 

My custom widget needs to draw some graphics on some kind of canvas. I see in the widgets.hpp file that I should never inherit from Widget itself, but from VirtualWidget. But presumably VirtualWidget itself is virtual and can't be instantiated.

What's the first concrete widget I can inherit from if I want to start with something that basically works and I can then start changing? Is it OpaqueWidget or FramebufferWidget?

**Comment by AndrewBelt** [comment]
All classes are concrete. You're confusing virtual with abstract. In Rack 0.6, inherit from `VirtualWidget`. Rack 1.0 removes virtual inheritance, so inherit simply from `Widget`.

**Comment by interstar** [comment]
OK ... I figured it out.

For my purposes it needed to be ParamWidget I was inheriting from.
