### ISSUE TITLE
Issue with the Template

### ISSUE THREAD

**Issue by max-circlefade** [VCVRack/Template#21]
Hi, 

I'm trying to get into vcv module dev, but already stuck at making the Template example.
Make dist returns:

```
Makefile:29: ../../plugin.mk: No such file or directory
make: *** No rule to make target `../../plugin.mk'.  Stop.
```

Does the template not run straight away (or I'm missing something)

Many thanks :)

**Comment by AndrewBelt** [comment]
When using the Rack SDK, you need to define `RACK_DIR` with either `RACK_DIR=... make dist` or `export RACK_DIR=...` in your shell config (`.bash_profile` or something).

**Comment by max-circlefade** [comment]
Thanks :)
